/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 *
 ******************************************************************************
 */

#include "std_types.h"
#include "rcc.h"
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void TEST_RCC_AHB1_enableCLock(void);
void TEST_RCC_HSEBypass(void);
void TEST_RCC_setCLockStatus(void);


int main(void)
{
	TEST_RCC_AHB1_enableCLock();
	TEST_RCC_HSEBypass();
	TEST_RCC_setCLockStatus();
    /* Loop forever */
	for(;;);
}


/*******************************************************
 * 					RCC driver tests				   *
 *******************************************************/

void TEST_RCC_AHB1_enableCLock(void)
{
	volatile uint8 gpioAEnableResult = 8;
	gpioAEnableResult = RCC_AHB1_enableClock(GPIOA);
	if(gpioAEnableResult == TRUE)
	{
		printf("RCC_AHB1_enableClock test passed\n");
	}
	else
	{
		printf("RCC_AHB1_enableClock test failed\n");
	}

	gpioAEnableResult = 8;
	gpioAEnableResult = RCC_AHB1_disableClock(GPIOA);
	if(gpioAEnableResult == TRUE)
	{
		printf("RCC_AHB1_disableClock test passed\n");
	}
	else
	{
		printf("RCC_AHB1_disableClock test failed\n");
	}
}


void TEST_RCC_HSEBypass(void)
{
	volatile bool bypassResult = 8;
	bypassResult = RCC_HSEBypass(TRUE);
	if(bypassResult == TRUE)
	{
		printf("RCC_HSEBypass(TRUE) test passed\n");
	}
	else
	{
		printf("RCC_HSEBypass(TRUE) test failed\n");
	}

	bypassResult = 8;
	bypassResult = RCC_HSEBypass(FALSE);
	if(bypassResult == TRUE)
	{
		printf("RCC_HSEBypass(FALSE) test passed\n");
	}
	else
	{
		printf("RCC_HSEBypass(FALSE) test failed\n");
	}
}


void TEST_RCC_setCLockStatus(void)
{
	volatile bool clkStatusResult = 8;
	clkStatusResult = RCC_setCLockStatus(HSE, ON);
	if(clkStatusResult == TRUE)
	{
		printf("RCC_setCLockStatus(HSE, ON) test passed\n");
	}
	else
	{
		printf("RCC_setCLockStatus(HSE, ON) test failed\n");
	}

	clkStatusResult = 8;
	clkStatusResult = RCC_setCLockStatus(HSE, OFF);
	if(clkStatusResult == TRUE)
	{
		printf("RCC_setCLockStatus(HSE, OFF) test passed\n");
	}
	else
	{
		printf("RCC_setCLockStatus(HSE, OFF) test failed\n");
	}
}
